apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::562190133801:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::562190133801:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2021-10-12T21:55:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "13062"
  uid: f3bcba4f-04be-49eb-b84d-f77f98aac4ef
